### ISSUE TITLE
屏蔽默认分组栏？

### ISSUE THREAD

**Issue by ghost** [tiansh/yawf#117]
![2018-12-27 10 44 22](https://user-images.githubusercontent.com/35698144/50463116-86201400-09c4-11e9-9fac-e8791457ee9b.png)
请问大家如何去除？

**Comment by tiansh** [comment]
分组可以点开你的关注列表在里面管理，包括删除某个分组。那个分组上面的小齿轮现在脚本没有提供选项给去掉，你可以暂时用这段自定义 CSS。没想好这东西要不要加一个设置项。

```css
#v6_pl_leftnav_group { display: none !important; }
```
