### ISSUE TITLE
置微博宽度和阅读视图宽度能否设置为比例

### ISSUE THREAD

**Issue by xqiushi** [tiansh/yawf#127]
置微博宽度和阅读视图宽度能否设置为比例而不是固定像素，因为有时候会外接屏，这样固定像素就起不了作用。谢谢

**Comment by tiansh** [comment]
我决定把阅读视图功能砍掉了，这样就没这个问题了，我真机智。

**Comment by tiansh** [comment]
4.0 之后可以通过自定义样式修改，样式如下：
```css
body[yawf-feed-only][yawf-feed-only] { --yawf-feed-width: 80vw; }
```
其中的 80 是宽度占屏幕宽度的百分比
