### ISSUE TITLE
建议「替换默认字体为」可自己输入字体名称

### ISSUE THREAD

**Issue by xingrz** [tiansh/yawf#32]
主要是选框里面没有「苹方」体，但考虑到苹方只对 OS X 用户有用，所以加个任意输入会好一点。

**Comment by tiansh** [comment]
自己可以输入的话做起来会很麻烦，而且这东西如果一定要很特别的字体，用自定义样式也可以解决。
```css
body, body.WB_macT, body.WB_xpT, .WB_webim { font-family: "Times New Roman", "SimSun"; }
```
类似这样就可以。

我把“苹方”加入到列表里面了，你更新到379版本应该就能看到了。不过因为我手头没苹果电脑，所以这功能我没试过，你试试看能不能用，不行的话我再更新。

这个列表会只显示你机器上可以检测到的字体，所以别的用户也不会受到影响，这点不用担心。
