### ISSUE TITLE
Possible workaround solvement for i18n problem

### ISSUE THREAD

**Issue by SilverBut** [tiansh/yawf#61]
微博对i18n支持不够好，没有添加<html lang='zh-cmn-Hans'>导致部分情况下调用了字体的非中文字形。如在我的机器上，会调用思源宋体的日文字形。
目前我通过一行JS解决了问题，不过不够优雅：
`document.getElementsByTagName('html')[0].setAttribute('lang','zh-cmn-Hans')`

**Comment by tiansh** [comment]
微博的文字主要可以分为两部分：
* 标题、按钮等由网站提供的文字
* 用户名、签名、用户消息等由用户内容提供的文字

其中第一项内容的语言是可控的，一共只有四种选择：`zh-CN`, `zh-HK`, `zh-TW`, `en`。
第二项内容的语言是不可控的，这受你自己和你关注的人使用何种语言影响而不同。

如果我将你要的功能理解为“根据选择的界面语言，添加对应语言标记“，那么这个功能应该写成

```javascript
document.documentElement.lang = unsafeWindow.$CONFIG.lang;
```

这样的问题自然就是，他只能提示浏览器网站提供的文字是哪种语言，但是却对用户产生的内容部分给出了可能错误的语言信息提示。

至于针对第二类内容，这应该超出了用户脚本应该处理的范围。

不知道你期望的功能是不是类似上面那样的实现。

----

另外，脚本设置网页使用哪种字体的功能是否可以通过指定字体的方式解决你的问题？

**Comment by tiansh** [comment]
简体中文思源宋体的话可以这样写自定义样式（注意写上 **SC** ，如果 SC 不管用，你可以试试改成 CN ）

```css
body, body.WB_macT, body.WB_xpT, .WB_webim { font-family: Georgia, "Noto Serif CJK SC", "Source Han Serif SC", serif; }
```
