### ISSUE TITLE
功能建议：在默认提供的“替换字体”选择菜单中增加"Source Sans Pro"

### ISSUE THREAD

**Issue by XiDeAssassin** [tiansh/yawf#62]
以前自己改一次能用挺长时间的，最近更新比较频繁了就有时会失效。
另外 m.weibo.cn/beta 这个版本的微博提供了正常的时间轴，不知道能否利用上

**Comment by tiansh** [comment]
如果想自己加其实加自定义样式更靠谱。

现在字体的逻辑是每次打开网页都要检查一遍字体是否存在，检查的方法也挺慢的。加太多恐怕会影响性能。而且一下没什么好主意要怎么弄……

**Comment by XiDeAssassin** [comment]
谢谢回复，我去学习一下自定义CSS

**Comment by tiansh** [comment]
```css
body, body.WB_macT, body.WB_xpT, .WB_webim {font-family: 在这里写字体;}
```

**Comment by tiansh** [comment]
```css
body, body.WB_macT, body.WB_xpT, .WB_webim {font-family: 在这里写字体;}
```
